services:
  postgres-database:
    image: bitnami/postgresql:latest
    container_name: postgresql
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: apishoppertest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

  api:
    image: node:22-alpine
    container_name: api
    working_dir: /api
    environment:
      DATABASE_URL: 'postgresql://docker:docker@postgres-database:5432/apishoppertest?schema=public'
      GEMINI_API: 'AIzaSyC0PIbprf9VP4U1yWc8R6rxOguLlRHq4fc'
    ports:
      - "3333:3333"
    entrypoint: >
      sh -c "
        npm install &&
        npx prisma generate
        npx prisma migrate deploy &&
        npm run dev
      "
    depends_on:
      - postgres-database
    volumes:
      - .:/api

volumes:
  postgres_data:
